apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres
spec:
 replicas: 1
 selector:
  matchLabels:
   app: postgres
 template:
  metadata:
   labels:
    app: postgres
  spec:
   containers:
    - name: postgres
      image: postgres:16
      env:
       - name: POSTGRES_DB
         value: "moviesdb"
       - name: POSTGRES_USER
         value: "movieuser"
       - name: POSTGRES_PASSWORD
         value: "password123"
      ports:
       - containerPort: 5432
      volumeMounts:
       - name: postgres-data
         mountPath: /var/lib/postgresql/data
   volumes:
    - name: postgres-data
      emptyDir: {} # For learning; in real life, use PersistentVolumeClaim
