# Stage 1: Build the Angular app
FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --output-path=dist

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Copy built Angular app to Nginx html directory
COPY --from=build /app/dist/movie-frontend/browser /usr/share/nginx/html

# Copy custom entrypoint for injecting env.js
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Copy the default nginx config (optional, if you need custom config)
# COPY nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT ["/docker-entrypoint.sh"]
