apiVersion: v1
kind: Pod
metadata:
 name: backend
spec:
 containers:
  - name: backend
    image: movie-backend:latest
    imagePullPolicy: IfNotPresent
    env:
     - name: DB_HOST
       value: "postgres" # This matches the Postgres service name!
     - name: DB_NAME
       value: "moviesdb"
     - name: DB_USER
       value: "movieuser"
     - name: DB_PASSWORD
       value: "password123"
    ports:
     - containerPort: 8000
